import type { InsertEvent } from "~/server/db/schema/events.ts";

export const eventsStub: InsertEvent[] = [
  ///////////////////////////////////////////////////////////////////
  // Unofficial
  ///////////////////////////////////////////////////////////////////
  {
    eventId: "fto",
    name: "Face-Turning Octahedron",
    rank: 1010,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 1,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "333_team_bld",
    name: "3x3x3 Team-Blind",
    rank: 1020,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 1,
    participants: 2,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "333_mirror_blocks",
    name: "Mirror Blocks",
    rank: 1030,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 1,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "magic",
    name: "Magic",
    rank: 1040,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 1,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "mmagic",
    name: "Master Magic",
    rank: 1050,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 1,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "333ft",
    name: "3x3x3 With Feet",
    rank: 1060,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 1,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  ///////////////////////////////////////////////////////////////////
  // WCA
  ///////////////////////////////////////////////////////////////////
  {
    eventId: "333",
    name: "3x3x3 Cube",
    rank: 10,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "222",
    name: "2x2x2 Cube",
    rank: 20,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "444",
    name: "4x4x4 Cube",
    rank: 30,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "555",
    name: "5x5x5 Cube",
    rank: 40,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "666",
    name: "6x6x6 Cube",
    rank: 50,
    format: "time" as const,
    defaultRoundFormat: "m" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "777",
    name: "7x7x7 Cube",
    rank: 60,
    format: "time" as const,
    defaultRoundFormat: "m" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "333bf",
    name: "3x3x3 Blindfolded",
    rank: 70,
    format: "time" as const,
    defaultRoundFormat: "3" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: true,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "333fm",
    name: "3x3x3 Fewest Moves",
    rank: 80,
    format: "number" as const,
    defaultRoundFormat: "m" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "333oh",
    name: "3x3x3 One-Handed",
    rank: 90,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "clock",
    name: "Clock",
    rank: 110,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "minx",
    name: "Megaminx",
    rank: 120,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "pyram",
    name: "Pyraminx",
    rank: 130,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "skewb",
    name: "Skewb",
    rank: 140,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "sq1",
    name: "Square-1",
    rank: 150,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 2,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "444bf",
    name: "4x4x4 Blindfolded",
    rank: 160,
    format: "time" as const,
    defaultRoundFormat: "3" as const,
    categoryId: 2,
    hasMemo: true,
    submissionsAllowed: true,
    participants: 1,
    hidden: false,
  },
  {
    eventId: "555bf",
    name: "5x5x5 Blindfolded",
    rank: 170,
    format: "time" as const,
    defaultRoundFormat: "3" as const,
    categoryId: 2,
    submissionsAllowed: true,
    hasMemo: true,
    hidden: false,
    participants: 1,
  },
  {
    eventId: "333mbf",
    name: "3x3x3 Multi-Blind",
    rank: 180,
    format: "multi" as const,
    defaultRoundFormat: "1" as const,
    categoryId: 2,
    submissionsAllowed: true,
    hasMemo: true,
    hidden: false,
    participants: 1,
  },
  ///////////////////////////////////////////////////////////////////
  // Extreme BLD
  ///////////////////////////////////////////////////////////////////
  {
    eventId: "333mbo",
    name: "3x3x3 Multi-Blind Old Style",
    rank: 2010,
    format: "multi" as const,
    defaultRoundFormat: "1" as const,
    categoryId: 3,
    hasMemo: true,
    participants: 1,
    submissionsAllowed: true,
    hidden: false,
  },
  {
    eventId: "666bf",
    name: "6x6x6 Blindfolded",
    rank: 2100,
    format: "time" as const,
    defaultRoundFormat: "1" as const,
    categoryId: 3,
    hasMemo: true,
    participants: 1,
    submissionsAllowed: true,
    hidden: false,
  },
  {
    eventId: "777bf",
    name: "7x7x7 Blindfolded",
    rank: 2110,
    format: "time" as const,
    defaultRoundFormat: "1" as const,
    categoryId: 3,
    hasMemo: true,
    participants: 1,
    submissionsAllowed: true,
    hidden: false,
  },
  ///////////////////////////////////////////////////////////////////
  // Miscellaneous
  ///////////////////////////////////////////////////////////////////
  {
    eventId: "234relay",
    name: "2x2x2-4x4x4 Relay",
    rank: 3010,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 4,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "gigaminx",
    name: "Gigaminx",
    rank: 3020,
    format: "time" as const,
    defaultRoundFormat: "a" as const,
    categoryId: 4,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
  },
  {
    eventId: "333bf_2_person_relay",
    name: "3x3x3 Blindfolded 2-man Relay",
    rank: 3030,
    format: "time" as const,
    defaultRoundFormat: "1" as const,
    categoryId: 4,
    participants: 2,
    hasMemo: false,
    submissionsAllowed: true,
    hidden: false,
  },
  {
    eventId: "333_oh_bld_team_relay",
    name: "3x3x3 + OH + BLD Team Relay",
    rank: 3040,
    format: "time" as const,
    defaultRoundFormat: "3" as const,
    categoryId: 4,
    participants: 3,
    hasMemo: false,
    submissionsAllowed: true,
    hidden: false,
  },
].map((e) => ({ ...e, organizationId: "default" }));
