import type { InsertEvent } from "~/server/db/schema/events.ts";

export const eventsStub = (): InsertEvent[] => [
  ///////////////////////////////////////////////////////////////////
  // WCA
  ///////////////////////////////////////////////////////////////////
  {
    eventId: "333",
    name: "3x3x3 Cube",
    rank: 10,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "222",
    name: "2x2x2 Cube",
    rank: 20,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "444",
    name: "4x4x4 Cube",
    rank: 30,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "555",
    name: "5x5x5 Cube",
    rank: 40,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "666",
    name: "6x6x6 Cube",
    rank: 50,
    format: "time",
    defaultRoundFormat: "m",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "777",
    name: "7x7x7 Cube",
    rank: 60,
    format: "time",
    defaultRoundFormat: "m",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "333bf",
    name: "3x3x3 Blindfolded",
    rank: 70,
    format: "time",
    defaultRoundFormat: "3",
    category: "wca",
    participants: 1,
    hasMemo: true,
    removedWca: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "333fm",
    name: "3x3x3 Fewest Moves",
    rank: 80,
    format: "number",
    defaultRoundFormat: "m",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "333oh",
    name: "3x3x3 One-Handed",
    rank: 90,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "clock",
    name: "Clock",
    rank: 110,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "minx",
    name: "Megaminx",
    rank: 120,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "pyram",
    name: "Pyraminx",
    rank: 130,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "skewb",
    name: "Skewb",
    rank: 140,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "sq1",
    name: "Square-1",
    rank: 150,
    format: "time",
    defaultRoundFormat: "a",
    category: "wca",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "444bf",
    name: "4x4x4 Blindfolded",
    rank: 160,
    format: "time",
    defaultRoundFormat: "3",
    category: "wca",
    hasMemo: true,
    submissionsAllowed: true,
    participants: 1,
    removedWca: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "555bf",
    name: "5x5x5 Blindfolded",
    rank: 170,
    format: "time",
    defaultRoundFormat: "3",
    category: "wca",
    submissionsAllowed: true,
    hasMemo: true,
    hidden: false,
    removedWca: false,
    description: "",
    participants: 1,
  },
  {
    eventId: "333mbf",
    name: "3x3x3 Multi-Blind",
    rank: 180,
    format: "multi",
    defaultRoundFormat: "1",
    category: "wca",
    submissionsAllowed: true,
    hasMemo: true,
    removedWca: false,
    hidden: false,
    description: "",
    participants: 1,
  },
  ///////////////////////////////////////////////////////////////////
  // Unofficial
  ///////////////////////////////////////////////////////////////////
  {
    eventId: "fto",
    name: "Face-Turning Octahedron",
    rank: 1010,
    format: "time",
    defaultRoundFormat: "a",
    category: "unofficial",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "333_team_bld",
    name: "3x3x3 Team-Blind",
    rank: 1020,
    format: "time",
    defaultRoundFormat: "a",
    category: "unofficial",
    participants: 2,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "333_mirror_blocks",
    name: "Mirror Blocks",
    rank: 1030,
    format: "time",
    defaultRoundFormat: "a",
    category: "unofficial",
    participants: 1,
    removedWca: false,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "magic",
    name: "Magic",
    rank: 1040,
    format: "time",
    defaultRoundFormat: "a",
    category: "unofficial",
    removedWca: true,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "mmagic",
    name: "Master Magic",
    rank: 1050,
    format: "time",
    defaultRoundFormat: "a",
    category: "unofficial",
    removedWca: true,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "333ft",
    name: "3x3x3 With Feet",
    rank: 1060,
    format: "time",
    defaultRoundFormat: "a",
    category: "unofficial",
    removedWca: true,
    participants: 1,
    hasMemo: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  ///////////////////////////////////////////////////////////////////
  // Extreme BLD
  ///////////////////////////////////////////////////////////////////
  {
    eventId: "333mbo",
    name: "3x3x3 Multi-Blind Old Style",
    rank: 2010,
    format: "multi",
    defaultRoundFormat: "1",
    category: "extreme-bld",
    hasMemo: true,
    removedWca: true,
    participants: 1,
    submissionsAllowed: true,
    hidden: false,
    description: "",
  },
  {
    eventId: "666bf",
    name: "6x6x6 Blindfolded",
    rank: 2100,
    format: "time",
    defaultRoundFormat: "1",
    category: "extreme-bld",
    hasMemo: true,
    participants: 1,
    removedWca: false,
    submissionsAllowed: true,
    hidden: false,
    description: "",
  },
  {
    eventId: "777bf",
    name: "7x7x7 Blindfolded",
    rank: 2110,
    format: "time",
    defaultRoundFormat: "1",
    category: "extreme-bld",
    hasMemo: true,
    participants: 1,
    removedWca: false,
    submissionsAllowed: true,
    hidden: false,
    description: "",
  },
  ///////////////////////////////////////////////////////////////////
  // Miscellaneous
  ///////////////////////////////////////////////////////////////////
  {
    eventId: "234relay",
    name: "2x2x2-4x4x4 Relay",
    rank: 3010,
    format: "time",
    defaultRoundFormat: "a",
    category: "miscellaneous",
    participants: 1,
    hasMemo: false,
    removedWca: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "gigaminx",
    name: "Gigaminx",
    rank: 3020,
    format: "time",
    defaultRoundFormat: "a",
    category: "miscellaneous",
    participants: 1,
    hasMemo: false,
    removedWca: false,
    submissionsAllowed: false,
    hidden: false,
    description: "",
  },
  {
    eventId: "333bf_2_person_relay",
    name: "3x3x3 Blindfolded 2-man Relay",
    rank: 3030,
    format: "time",
    defaultRoundFormat: "1",
    category: "miscellaneous",
    participants: 2,
    hasMemo: false,
    removedWca: false,
    submissionsAllowed: true,
    hidden: false,
    description: "",
  },
];
