// See https://www.countrycallingcodes.com/iso-country-codes/

const Countries = [
  { name: "Afghanistan", code: "AF", continent: "AS" },
  { name: "Albania", code: "AL", continent: "EU" },
  { name: "Algeria", code: "DZ", continent: "AF" },
  { name: "Andorra", code: "AD", continent: "EU" },
  { name: "Angola", code: "AO", continent: "AF" },
  { name: "Antigua and Barbuda", code: "AG", continent: "NA" },
  { name: "Argentina", code: "AR", continent: "SA" },
  { name: "Armenia", code: "AM", continent: "AS" },
  { name: "Australia", code: "AU", continent: "OC" },
  { name: "Austria", code: "AT", continent: "EU" },
  { name: "Azerbaijan", code: "AZ", continent: "AS" },
  { name: "Bahamas", code: "BS", continent: "NA" },
  { name: "Bahrain", code: "BH", continent: "AS" },
  { name: "Bangladesh", code: "BD", continent: "AS" },
  { name: "Barbados", code: "BB", continent: "NA" },
  { name: "Belarus", code: "BY", continent: "EU" },
  { name: "Belgium", code: "BE", continent: "EU" },
  { name: "Belize", code: "BZ", continent: "NA" },
  { name: "Benin", code: "BJ", continent: "AF" },
  { name: "Bhutan", code: "BT", continent: "AS" },
  { name: "Bolivia", code: "BO", continent: "SA" },
  { name: "Bosnia and Herzegovina", code: "BA", continent: "EU" },
  { name: "Botswana", code: "BW", continent: "AF" },
  { name: "Brazil", code: "BR", continent: "SA" },
  { name: "Brunei", code: "BN", continent: "AS" },
  { name: "Bulgaria", code: "BG", continent: "EU" },
  { name: "Burkina Faso", code: "BF", continent: "AF" },
  { name: "Burundi", code: "BI", continent: "AF" },
  { name: "Cabo Verde", code: "CV", continent: "AF" },
  { name: "Cambodia", code: "KH", continent: "AS" },
  { name: "Cameroon", code: "CM", continent: "AF" },
  { name: "Canada", code: "CA", continent: "NA" },
  { name: "Central African Republic", code: "CF", continent: "AF" },
  { name: "Chad", code: "TD", continent: "AF" },
  { name: "Chile", code: "CL", continent: "SA" },
  { name: "China", code: "CN", continent: "AS" },
  { name: "Colombia", code: "CO", continent: "SA" },
  { name: "Comoros", code: "KM", continent: "AF" },
  { name: "Costa Rica", code: "CR", continent: "NA" },
  { name: "Côte d'Ivoire", code: "CI", continent: "AF" },
  { name: "Croatia", code: "HR", continent: "EU" },
  { name: "Cuba", code: "CU", continent: "NA" },
  { name: "Cyprus", code: "CY", continent: "EU" },
  { name: "Czechia", code: "CZ", continent: "EU" },
  { name: "Democratic Republic of the Congo", shortName: "DRC", code: "CD", continent: "AF" },
  { name: "Denmark", code: "DK", continent: "EU" },
  { name: "Djibouti", code: "DJ", continent: "AF" },
  { name: "Dominica", code: "DM", continent: "NA" },
  { name: "Dominican Republic", code: "DO", continent: "NA" },
  { name: "Ecuador", code: "EC", continent: "SA" },
  { name: "Egypt", code: "EG", continent: "AF" },
  { name: "El Salvador", code: "SV", continent: "NA" },
  { name: "Equatorial Guinea", code: "GQ", continent: "AF" },
  { name: "Eritrea", code: "ER", continent: "AF" },
  { name: "Estonia", code: "EE", continent: "EU" },
  { name: "Eswatini", code: "SZ", continent: "AF" },
  { name: "Ethiopia", code: "ET", continent: "AF" },
  { name: "Fiji", code: "FJ", continent: "OC" },
  { name: "Finland", code: "FI", continent: "EU" },
  { name: "France", code: "FR", continent: "EU" },
  { name: "Gabon", code: "GA", continent: "AF" },
  { name: "Gambia", code: "GM", continent: "AF" },
  { name: "Georgia", code: "GE", continent: "AS" },
  { name: "Germany", code: "DE", continent: "EU" },
  { name: "Ghana", code: "GH", continent: "AF" },
  { name: "Greece", code: "GR", continent: "EU" },
  { name: "Grenada", code: "GD", continent: "NA" },
  { name: "Guatemala", code: "GT", continent: "NA" },
  { name: "Guinea", code: "GN", continent: "AF" },
  { name: "Guinea Bissau", code: "GW", continent: "AF" },
  { name: "Guyana", code: "GY", continent: "SA" },
  { name: "Haiti", code: "HT", continent: "NA" },
  { name: "Honduras", code: "HN", continent: "NA" },
  { name: "Hong Kong", code: "HK", continent: "AS" },
  { name: "Hungary", code: "HU", continent: "EU" },
  { name: "Iceland", code: "IS", continent: "EU" },
  { name: "India", code: "IN", continent: "AS" },
  { name: "Indonesia", code: "ID", continent: "AS" },
  { name: "Iran", code: "IR", continent: "AS" },
  { name: "Iraq", code: "IQ", continent: "AS" },
  { name: "Ireland", code: "IE", continent: "EU" },
  { name: "Israel", code: "IL", continent: "AS" },
  { name: "Italy", code: "IT", continent: "EU" },
  { name: "Jamaica", code: "JM", continent: "NA" },
  { name: "Japan", code: "JP", continent: "AS" },
  { name: "Jordan", code: "JO", continent: "AS" },
  { name: "Kazakhstan", code: "KZ", continent: "AS" },
  { name: "Kenya", code: "KE", continent: "AF" },
  { name: "Kiribati", code: "KI", continent: "OC" },
  { name: "Kosovo", code: "XK", continent: "EU" },
  { name: "Kuwait", code: "KW", continent: "AS" },
  { name: "Kyrgyzstan", code: "KG", continent: "AS" },
  { name: "Laos", code: "LA", continent: "AS" },
  { name: "Latvia", code: "LV", continent: "EU" },
  { name: "Lebanon", code: "LB", continent: "AS" },
  { name: "Lesotho", code: "LS", continent: "AF" },
  { name: "Liberia", code: "LR", continent: "AF" },
  { name: "Libya", code: "LY", continent: "AF" },
  { name: "Liechtenstein", code: "LI", continent: "EU" },
  { name: "Lithuania", code: "LT", continent: "EU" },
  { name: "Luxembourg", code: "LU", continent: "EU" },
  { name: "Macau", code: "MO", continent: "AS" },
  { name: "Madagascar", code: "MG", continent: "AF" },
  { name: "Malawi", code: "MW", continent: "AF" },
  { name: "Malaysia", code: "MY", continent: "AS" },
  { name: "Maldives", code: "MV", continent: "AS" },
  { name: "Mali", code: "ML", continent: "AF" },
  { name: "Malta", code: "MT", continent: "EU" },
  { name: "Marshall Islands", code: "MH", continent: "OC" },
  { name: "Mauritania", code: "MR", continent: "AF" },
  { name: "Mauritius", code: "MU", continent: "AF" },
  { name: "Mexico", code: "MX", continent: "NA" },
  { name: "Micronesia", code: "FM", continent: "OC" },
  { name: "Moldova", code: "MD", continent: "EU" },
  { name: "Monaco", code: "MC", continent: "EU" },
  { name: "Mongolia", code: "MN", continent: "AS" },
  { name: "Montenegro", code: "ME", continent: "EU" },
  { name: "Morocco", code: "MA", continent: "AF" },
  { name: "Mozambique", code: "MZ", continent: "AF" },
  { name: "Myanmar", code: "MM", continent: "AS" },
  { name: "Namibia", code: "NA", continent: "AF" },
  { name: "Nauru", code: "NR", continent: "OC" },
  { name: "Nepal", code: "NP", continent: "AS" },
  { name: "Netherlands", code: "NL", continent: "EU" },
  { name: "New Zealand", code: "NZ", continent: "OC" },
  { name: "Nicaragua", code: "NI", continent: "NA" },
  { name: "Niger", code: "NE", continent: "AF" },
  { name: "Nigeria", code: "NG", continent: "AF" },
  { name: "North Korea", code: "KP", continent: "AS" },
  { name: "North Macedonia", code: "MK", continent: "EU" },
  { name: "Norway", code: "NO", continent: "EU" },
  { name: "Oman", code: "OM", continent: "AS" },
  { name: "Pakistan", code: "PK", continent: "AS" },
  { name: "Palau", code: "PW", continent: "OC" },
  { name: "Palestine", code: "PS", continent: "AS" },
  { name: "Panama", code: "PA", continent: "NA" },
  { name: "Papua New Guinea", code: "PG", continent: "OC" },
  { name: "Paraguay", code: "PY", continent: "SA" },
  { name: "Peru", code: "PE", continent: "SA" },
  { name: "Philippines", code: "PH", continent: "AS" },
  { name: "Poland", code: "PL", continent: "EU" },
  { name: "Portugal", code: "PT", continent: "EU" },
  { name: "Qatar", code: "QA", continent: "AS" },
  { name: "Republic of the Congo", code: "CG", continent: "AF" },
  { name: "Romania", code: "RO", continent: "EU" },
  { name: "Russia", code: "RU", continent: "EU" },
  { name: "Rwanda", code: "RW", continent: "AF" },
  { name: "Saint Kitts and Nevis", code: "KN", continent: "NA" },
  { name: "Saint Lucia", code: "LC", continent: "NA" },
  { name: "Saint Vincent and the Grenadines", code: "VC", continent: "NA" },
  { name: "Samoa", code: "WS", continent: "OC" },
  { name: "San Marino", code: "SM", continent: "EU" },
  { name: "São Tomé and Príncipe", code: "ST", continent: "AF" },
  { name: "Saudi Arabia", code: "SA", continent: "AS" },
  { name: "Senegal", code: "SN", continent: "AF" },
  { name: "Serbia", code: "RS", continent: "EU" },
  { name: "Seychelles", code: "SC", continent: "AF" },
  { name: "Sierra Leone", code: "SL", continent: "AF" },
  { name: "Singapore", code: "SG", continent: "AS" },
  { name: "Slovakia", code: "SK", continent: "EU" },
  { name: "Slovenia", code: "SI", continent: "EU" },
  { name: "Solomon Islands", code: "SB", continent: "OC" },
  { name: "Somalia", code: "SO", continent: "AF" },
  { name: "South Africa", code: "ZA", continent: "AF" },
  { name: "South Korea", code: "KR", continent: "AS" },
  { name: "South Sudan", code: "SS", continent: "AF" },
  { name: "Spain", code: "ES", continent: "EU" },
  { name: "Sri Lanka", code: "LK", continent: "AS" },
  { name: "Sudan", code: "SD", continent: "AF" },
  { name: "Suriname", code: "SR", continent: "SA" },
  { name: "Sweden", code: "SE", continent: "EU" },
  { name: "Switzerland", code: "CH", continent: "EU" },
  { name: "Syria", code: "SY", continent: "AS" },
  { name: "Taiwan", code: "TW", continent: "AS" },
  { name: "Tajikistan", code: "TJ", continent: "AS" },
  { name: "Tanzania", code: "TZ", continent: "AF" },
  { name: "Thailand", code: "TH", continent: "AS" },
  { name: "Timor-Leste", code: "TL", continent: "OC" },
  { name: "Togo", code: "TG", continent: "AF" },
  { name: "Tonga", code: "TO", continent: "OC" },
  { name: "Trinidad and Tobago", code: "TT", continent: "NA" },
  { name: "Tunisia", code: "TN", continent: "AF" },
  { name: "Turkmenistan", code: "TM", continent: "AS" },
  { name: "Tuvalu", code: "TV", continent: "OC" },
  { name: "Türkiye", code: "TR", continent: "AS" },
  { name: "Uganda", code: "UG", continent: "AF" },
  { name: "Ukraine", code: "UA", continent: "EU" },
  { name: "United Arab Emirates", shortName: "UAE", code: "AE", continent: "AS" },
  { name: "United Kingdom", shortName: "UK", code: "GB", continent: "EU" },
  { name: "United States", shortName: "USA", code: "US", continent: "NA" },
  { name: "Uruguay", code: "UY", continent: "SA" },
  { name: "Uzbekistan", code: "UZ", continent: "AS" },
  { name: "Vanuatu", code: "VU", continent: "OC" },
  { name: "Vatican City", code: "VA", continent: "EU" },
  { name: "Venezuela", code: "VE", continent: "SA" },
  { name: "Vietnam", code: "VN", continent: "AS" },
  { name: "Yemen", code: "YE", continent: "AS" },
  { name: "Zambia", code: "ZM", continent: "AF" },
  { name: "Zimbabwe", code: "ZW", continent: "AF" },
];

export default Countries;
