// See https://www.countrycallingcodes.com/iso-country-codes/

const Countries = [
  { name: "Afghanistan", code: "AF", continentId: "AS" },
  { name: "Albania", code: "AL", continentId: "EU" },
  { name: "Algeria", code: "DZ", continentId: "AF" },
  { name: "Andorra", code: "AD", continentId: "EU" },
  { name: "Angola", code: "AO", continentId: "AF" },
  { name: "Antigua and Barbuda", code: "AG", continentId: "NA" },
  { name: "Argentina", code: "AR", continentId: "SA" },
  { name: "Armenia", code: "AM", continentId: "AS" },
  { name: "Australia", code: "AU", continentId: "OC" },
  { name: "Austria", code: "AT", continentId: "EU" },
  { name: "Azerbaijan", code: "AZ", continentId: "AS" },
  { name: "Bahamas", code: "BS", continentId: "NA" },
  { name: "Bahrain", code: "BH", continentId: "AS" },
  { name: "Bangladesh", code: "BD", continentId: "AS" },
  { name: "Barbados", code: "BB", continentId: "NA" },
  { name: "Belarus", code: "BY", continentId: "EU" },
  { name: "Belgium", code: "BE", continentId: "EU" },
  { name: "Belize", code: "BZ", continentId: "NA" },
  { name: "Benin", code: "BJ", continentId: "AF" },
  { name: "Bhutan", code: "BT", continentId: "AS" },
  { name: "Bolivia", code: "BO", continentId: "SA" },
  { name: "Bosnia and Herzegovina", code: "BA", continentId: "EU" },
  { name: "Botswana", code: "BW", continentId: "AF" },
  { name: "Brazil", code: "BR", continentId: "SA" },
  { name: "Brunei", code: "BN", continentId: "AS" },
  { name: "Bulgaria", code: "BG", continentId: "EU" },
  { name: "Burkina Faso", code: "BF", continentId: "AF" },
  { name: "Burundi", code: "BI", continentId: "AF" },
  { name: "Cabo Verde", code: "CV", continentId: "AF" },
  { name: "Cambodia", code: "KH", continentId: "AS" },
  { name: "Cameroon", code: "CM", continentId: "AF" },
  { name: "Canada", code: "CA", continentId: "NA" },
  { name: "Central African Republic", code: "CF", continentId: "AF" },
  { name: "Chad", code: "TD", continentId: "AF" },
  { name: "Chile", code: "CL", continentId: "SA" },
  { name: "China", code: "CN", continentId: "AS" },
  { name: "Colombia", code: "CO", continentId: "SA" },
  { name: "Comoros", code: "KM", continentId: "AF" },
  { name: "Costa Rica", code: "CR", continentId: "NA" },
  { name: "Côte d'Ivoire", code: "CI", continentId: "AF" },
  { name: "Croatia", code: "HR", continentId: "EU" },
  { name: "Cuba", code: "CU", continentId: "NA" },
  { name: "Cyprus", code: "CY", continentId: "EU" },
  { name: "Czechia", code: "CZ", continentId: "EU" },
  { name: "Democratic Republic of the Congo", shortName: "DRC", code: "CD", continentId: "AF" },
  { name: "Denmark", code: "DK", continentId: "EU" },
  { name: "Djibouti", code: "DJ", continentId: "AF" },
  { name: "Dominica", code: "DM", continentId: "NA" },
  { name: "Dominican Republic", code: "DO", continentId: "NA" },
  { name: "Ecuador", code: "EC", continentId: "SA" },
  { name: "Egypt", code: "EG", continentId: "AF" },
  { name: "El Salvador", code: "SV", continentId: "NA" },
  { name: "Equatorial Guinea", code: "GQ", continentId: "AF" },
  { name: "Eritrea", code: "ER", continentId: "AF" },
  { name: "Estonia", code: "EE", continentId: "EU" },
  { name: "Eswatini", code: "SZ", continentId: "AF" },
  { name: "Ethiopia", code: "ET", continentId: "AF" },
  { name: "Fiji", code: "FJ", continentId: "OC" },
  { name: "Finland", code: "FI", continentId: "EU" },
  { name: "France", code: "FR", continentId: "EU" },
  { name: "Gabon", code: "GA", continentId: "AF" },
  { name: "Gambia", code: "GM", continentId: "AF" },
  { name: "Georgia", code: "GE", continentId: "AS" },
  { name: "Germany", code: "DE", continentId: "EU" },
  { name: "Ghana", code: "GH", continentId: "AF" },
  { name: "Greece", code: "GR", continentId: "EU" },
  { name: "Grenada", code: "GD", continentId: "NA" },
  { name: "Guatemala", code: "GT", continentId: "NA" },
  { name: "Guinea", code: "GN", continentId: "AF" },
  { name: "Guinea Bissau", code: "GW", continentId: "AF" },
  { name: "Guyana", code: "GY", continentId: "SA" },
  { name: "Haiti", code: "HT", continentId: "NA" },
  { name: "Honduras", code: "HN", continentId: "NA" },
  { name: "Hong Kong", code: "HK", continentId: "AS" },
  { name: "Hungary", code: "HU", continentId: "EU" },
  { name: "Iceland", code: "IS", continentId: "EU" },
  { name: "India", code: "IN", continentId: "AS" },
  { name: "Indonesia", code: "ID", continentId: "AS" },
  { name: "Iran", code: "IR", continentId: "AS" },
  { name: "Iraq", code: "IQ", continentId: "AS" },
  { name: "Ireland", code: "IE", continentId: "EU" },
  { name: "Israel", code: "IL", continentId: "AS" },
  { name: "Italy", code: "IT", continentId: "EU" },
  { name: "Jamaica", code: "JM", continentId: "NA" },
  { name: "Japan", code: "JP", continentId: "AS" },
  { name: "Jordan", code: "JO", continentId: "AS" },
  { name: "Kazakhstan", code: "KZ", continentId: "AS" },
  { name: "Kenya", code: "KE", continentId: "AF" },
  { name: "Kiribati", code: "KI", continentId: "OC" },
  { name: "Kosovo", code: "XK", continentId: "EU" },
  { name: "Kuwait", code: "KW", continentId: "AS" },
  { name: "Kyrgyzstan", code: "KG", continentId: "AS" },
  { name: "Laos", code: "LA", continentId: "AS" },
  { name: "Latvia", code: "LV", continentId: "EU" },
  { name: "Lebanon", code: "LB", continentId: "AS" },
  { name: "Lesotho", code: "LS", continentId: "AF" },
  { name: "Liberia", code: "LR", continentId: "AF" },
  { name: "Libya", code: "LY", continentId: "AF" },
  { name: "Liechtenstein", code: "LI", continentId: "EU" },
  { name: "Lithuania", code: "LT", continentId: "EU" },
  { name: "Luxembourg", code: "LU", continentId: "EU" },
  { name: "Macau", code: "MO", continentId: "AS" },
  { name: "Madagascar", code: "MG", continentId: "AF" },
  { name: "Malawi", code: "MW", continentId: "AF" },
  { name: "Malaysia", code: "MY", continentId: "AS" },
  { name: "Maldives", code: "MV", continentId: "AS" },
  { name: "Mali", code: "ML", continentId: "AF" },
  { name: "Malta", code: "MT", continentId: "EU" },
  { name: "Marshall Islands", code: "MH", continentId: "OC" },
  { name: "Mauritania", code: "MR", continentId: "AF" },
  { name: "Mauritius", code: "MU", continentId: "AF" },
  { name: "Mexico", code: "MX", continentId: "NA" },
  { name: "Micronesia", code: "FM", continentId: "OC" },
  { name: "Moldova", code: "MD", continentId: "EU" },
  { name: "Monaco", code: "MC", continentId: "EU" },
  { name: "Mongolia", code: "MN", continentId: "AS" },
  { name: "Montenegro", code: "ME", continentId: "EU" },
  { name: "Morocco", code: "MA", continentId: "AF" },
  { name: "Mozambique", code: "MZ", continentId: "AF" },
  { name: "Myanmar", code: "MM", continentId: "AS" },
  { name: "Namibia", code: "NA", continentId: "AF" },
  { name: "Nauru", code: "NR", continentId: "OC" },
  { name: "Nepal", code: "NP", continentId: "AS" },
  { name: "Netherlands", code: "NL", continentId: "EU" },
  { name: "New Zealand", code: "NZ", continentId: "OC" },
  { name: "Nicaragua", code: "NI", continentId: "NA" },
  { name: "Niger", code: "NE", continentId: "AF" },
  { name: "Nigeria", code: "NG", continentId: "AF" },
  { name: "North Korea", code: "KP", continentId: "AS" },
  { name: "North Macedonia", code: "MK", continentId: "EU" },
  { name: "Norway", code: "NO", continentId: "EU" },
  { name: "Oman", code: "OM", continentId: "AS" },
  { name: "Pakistan", code: "PK", continentId: "AS" },
  { name: "Palau", code: "PW", continentId: "OC" },
  { name: "Palestine", code: "PS", continentId: "AS" },
  { name: "Panama", code: "PA", continentId: "NA" },
  { name: "Papua New Guinea", code: "PG", continentId: "OC" },
  { name: "Paraguay", code: "PY", continentId: "SA" },
  { name: "Peru", code: "PE", continentId: "SA" },
  { name: "Philippines", code: "PH", continentId: "AS" },
  { name: "Poland", code: "PL", continentId: "EU" },
  { name: "Portugal", code: "PT", continentId: "EU" },
  { name: "Qatar", code: "QA", continentId: "AS" },
  { name: "Republic of the Congo", code: "CG", continentId: "AF" },
  { name: "Romania", code: "RO", continentId: "EU" },
  { name: "Russia", code: "RU", continentId: "EU" },
  { name: "Rwanda", code: "RW", continentId: "AF" },
  { name: "Saint Kitts and Nevis", code: "KN", continentId: "NA" },
  { name: "Saint Lucia", code: "LC", continentId: "NA" },
  { name: "Saint Vincent and the Grenadines", code: "VC", continentId: "NA" },
  { name: "Samoa", code: "WS", continentId: "OC" },
  { name: "San Marino", code: "SM", continentId: "EU" },
  { name: "São Tomé and Príncipe", code: "ST", continentId: "AF" },
  { name: "Saudi Arabia", code: "SA", continentId: "AS" },
  { name: "Senegal", code: "SN", continentId: "AF" },
  { name: "Serbia", code: "RS", continentId: "EU" },
  { name: "Seychelles", code: "SC", continentId: "AF" },
  { name: "Sierra Leone", code: "SL", continentId: "AF" },
  { name: "Singapore", code: "SG", continentId: "AS" },
  { name: "Slovakia", code: "SK", continentId: "EU" },
  { name: "Slovenia", code: "SI", continentId: "EU" },
  { name: "Solomon Islands", code: "SB", continentId: "OC" },
  { name: "Somalia", code: "SO", continentId: "AF" },
  { name: "South Africa", code: "ZA", continentId: "AF" },
  { name: "South Korea", code: "KR", continentId: "AS" },
  { name: "South Sudan", code: "SS", continentId: "AF" },
  { name: "Spain", code: "ES", continentId: "EU" },
  { name: "Sri Lanka", code: "LK", continentId: "AS" },
  { name: "Sudan", code: "SD", continentId: "AF" },
  { name: "Suriname", code: "SR", continentId: "SA" },
  { name: "Sweden", code: "SE", continentId: "EU" },
  { name: "Switzerland", code: "CH", continentId: "EU" },
  { name: "Syria", code: "SY", continentId: "AS" },
  { name: "Taiwan", code: "TW", continentId: "AS" },
  { name: "Tajikistan", code: "TJ", continentId: "AS" },
  { name: "Tanzania", code: "TZ", continentId: "AF" },
  { name: "Thailand", code: "TH", continentId: "AS" },
  { name: "Timor-Leste", code: "TL", continentId: "AS" },
  { name: "Togo", code: "TG", continentId: "AF" },
  { name: "Tonga", code: "TO", continentId: "OC" },
  { name: "Trinidad and Tobago", code: "TT", continentId: "NA" },
  { name: "Tunisia", code: "TN", continentId: "AF" },
  { name: "Turkmenistan", code: "TM", continentId: "AS" },
  { name: "Tuvalu", code: "TV", continentId: "OC" },
  { name: "Türkiye", code: "TR", continentId: "AS" },
  { name: "Uganda", code: "UG", continentId: "AF" },
  { name: "Ukraine", code: "UA", continentId: "EU" },
  { name: "United Arab Emirates", shortName: "UAE", code: "AE", continentId: "AS" },
  { name: "United Kingdom", shortName: "UK", code: "GB", continentId: "EU" },
  { name: "United States", shortName: "USA", code: "US", continentId: "NA" },
  { name: "Uruguay", code: "UY", continentId: "SA" },
  { name: "Uzbekistan", code: "UZ", continentId: "AS" },
  { name: "Vanuatu", code: "VU", continentId: "OC" },
  { name: "Vatican City", code: "VA", continentId: "EU" },
  { name: "Venezuela", code: "VE", continentId: "SA" },
  { name: "Vietnam", code: "VN", continentId: "AS" },
  { name: "Yemen", code: "YE", continentId: "AS" },
  { name: "Zambia", code: "ZM", continentId: "AF" },
  { name: "Zimbabwe", code: "ZW", continentId: "AF" },
];

export default Countries;
