services:
  mongo:
    container_name: cc-mongo-dev
    image: mongo
    networks:
      - cubingcontests-dev
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - cubingcontests-db-dev:/data/db:rw
      - mongo-init:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ADMIN_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ADMIN_PASSWORD
      - MONGO_DEV_USERNAME=$MONGO_DEV_USERNAME
      - MONGO_DEV_PASSWORD=$MONGO_DEV_PASSWORD
    restart: unless-stopped

  mongo-express:
    container_name: cc-mongo-express
    image: mongo-express
    networks:
      - cubingcontests-dev
    ports:
      - 127.0.0.1:8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=cc-mongo-dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_ADMIN_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_ADMIN_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=cc
    depends_on:
      - mongo
    restart: unless-stopped

networks:
  cubingcontests-dev:
volumes:
  cubingcontests-db-dev:
    # Tells docker to create the storage for the volume on the local file system
    driver: local
  mongo-init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongo_init
