name: recordranks

services:
  nextjs:
    container_name: rr-nextjs
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - 127.0.0.1:${NEXTJS_PORT}:3000
    environment:
      PROD_HOSTNAME: ${PROD_HOSTNAME}
      INSTANCE_MAINTAINER_EMAIL: ${INSTANCE_MAINTAINER_EMAIL}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      WCA_OAUTH_CLIENT_ID: ${WCA_OAUTH_CLIENT_ID}
      WCA_OAUTH_SECRET: ${WCA_OAUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      # SEO variables
      METADATA_DESCRIPTION: ${METADATA_DESCRIPTION}
      METADATA_CONTESTS_DESCRIPTION: ${METADATA_CONTESTS_DESCRIPTION}
      METADATA_RANKINGS_DESCRIPTION: ${METADATA_RANKINGS_DESCRIPTION}
      METADATA_RECORDS_DESCRIPTION: ${METADATA_RECORDS_DESCRIPTION}
      METADATA_RULES_DESCRIPTION: ${METADATA_RULES_DESCRIPTION}
      METADATA_POSTS_DESCRIPTION: ${METADATA_POSTS_DESCRIPTION}
      METADATA_ABOUT_DESCRIPTION: ${METADATA_ABOUT_DESCRIPTION}
      METADATA_EXPORTS_DESCRIPTION: ${METADATA_EXPORTS_DESCRIPTION}
      ANALYTICS_SCRIPT_SRC: ${ANALYTICS_SCRIPT_SRC}
      ANALYTICS_SCRIPT_CONTENT: ${ANALYTICS_SCRIPT_CONTENT}

      # Variables for the DB connection string
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

      # Supabase variables
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      SUPABASE_STORAGE_URL: ${SUPABASE_STORAGE_URL}
      PUBLIC_EXPORTS_BUCKET_NAME: ${PUBLIC_EXPORTS_BUCKET_NAME}
      LOGFLARE_API_BASE_URL: ${LOGFLARE_API_BASE_URL}
      LOGFLARE_PUBLIC_ACCESS_TOKEN: ${LOGFLARE_PUBLIC_ACCESS_TOKEN}

      # Stripe variables (only used for the RecordRanks Platform website)
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \"fetch('http://localhost:3000/api/healthcheck').then((r) => {if (r.status !== 200) throw new Error(r.status)})\""
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
