version: '3'
services:
  mongo:
    container_name: cc-mongo
    image: mongo
    networks:
      - cubingcontests
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - cubingcontests-db:/data/db:rw
      # The scripts in docker-entrypoint-initdb.d are run when the container and volume are first created
      - mongo-init:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ADMIN_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ADMIN_PASSWORD
      - MONGO_DEV_USERNAME=$MONGO_DEV_USERNAME
      - MONGO_DEV_PASSWORD=$MONGO_DEV_PASSWORD
    restart: unless-stopped
  mongo-express:
    container_name: cc-mongo-express
    image: mongo-express
    networks:
      - cubingcontests
    ports:
      - 127.0.0.1:8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=cc-mongo
      - ME_CONFIG_MONGODB_AUTH_USERNAME=$MONGO_ADMIN_USERNAME
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=$MONGO_ADMIN_PASSWORD
    depends_on:
      - mongo
    restart: unless-stopped
  cc-api:
    container_name: cc-api
    image: cubingcontests-api
    networks:
      - cubingcontests
    ports:
      - 127.0.0.1:5000:5000
    environment:
      - MONGODB_URI=mongodb://$MONGO_DEV_USERNAME:$MONGO_DEV_PASSWORD@cc-mongo:27017/cubingcontests
      - NODE_ENV=$NODE_ENV
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - mongo
    restart: unless-stopped
  cc-client:
    container_name: cc-client
    image: cubingcontests-client
    networks:
      - cubingcontests
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - mongo
      - cc-api
    restart: unless-stopped
networks:
  cubingcontests:
volumes:
  cubingcontests-db:
    driver: local
  mongo-init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongo_init
