services:
  postgres:
    container_name: cc-postgres-dev # if this is ever changed, make sure to update all references to the old container name
    image: postgres:17-alpine
    networks:
      - cubingcontests-dev
    ports:
      - 127.0.0.1:5432:5432 # if this is ever changed, make sure to update all references to the old port
    volumes:
      - pg:/var/lib/postgresql/data:rw
      - ${PWD}/db_utils/pg_init:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=$DB_ADMIN_USERNAME
      - POSTGRES_PASSWORD=$DB_ADMIN_PASSWORD
      - DB_USERNAME=$DB_USERNAME # used in ./pg_init scripts
      - DB_PASSWORD=$DB_PASSWORD # used in ./pg_init scripts
      - DB_NAME=$DB_NAME # used in ./pg_init scripts
    restart: unless-stopped
  dbgate:
    image: dbgate/dbgate
    networks:
      - cubingcontests-dev
    ports:
      - 8080:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con1
      LABEL_con1: Postgres
      SERVER_con1: postgres
      USER_con1: $DB_USERNAME
      PASSWORD_con1: $DB_PASSWORD
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
    restart: always


networks:
  cubingcontests-dev:
volumes:
  pg:
    driver: local
  dbgate-data:
    driver: local