export interface ICompetitionBase {
  competitionId: string;
  name: string;
  city: string;
  countryId: string; // 2 letter country code
  startDate: Date;
  endDate: Date;
  mainEventId: string;
}

interface ICompetition extends ICompetitionBase {
  // Both of these are only set if the competition results have been posted
  participants?: number;
  events?: {
    eventId: string;
    rounds: string[]; // array of round ids (the _id values generated by Mongo)
  }[];
}

export default ICompetition;
