apiVersion: apps/v1
kind: Deployment
metadata:
  name: recordranks-nextjs
  labels:
    app: recordranks-nextjs
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: recordranks-nextjs
  template:
    metadata:
      labels:
        app: recordranks-nextjs
    spec:
      containers:
        - name: nextjs
          image: __DOCKER_IMAGE_NAME__ # substituted in start-prod.sh
          imagePullPolicy: Always
          ports:
            - name: nextjs-port
              containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: recordranks-config
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: nextjs-port
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/healthcheck/ready
              port: nextjs-port
            initialDelaySeconds: 10
            periodSeconds: 10
