# Variables with the format __VAR__ in this file are substituted in start-prod.sh

apiVersion: v1
kind: Service
metadata:
  name: recordranks-service
spec:
  type: NodePort
  selector:
    app: recordranks-nextjs
  ports:
    - name: recordranks-port
      protocol: TCP
      port: 3000
      targetPort: nextjs-port
      nodePort: __PORT__
