import type { ContinentCode, RecordType } from "./types.ts";

export const Continents: {
  name: string;
  code: ContinentCode;
  recordTypeId: RecordType;
}[] = [
  { name: "Africa", code: "AFRICA", recordTypeId: "AfR" },
  { name: "Asia", code: "ASIA", recordTypeId: "AsR" },
  { name: "Europe", code: "EUROPE", recordTypeId: "ER" },
  { name: "North America", code: "NORTH_AMERICA", recordTypeId: "NAR" },
  { name: "Oceania", code: "OCEANIA", recordTypeId: "OcR" },
  { name: "South America", code: "SOUTH_AMERICA", recordTypeId: "SAR" },
];

export const ContinentRecordType: Record<ContinentCode, RecordType> = {
  AFRICA: "AfR",
  ASIA: "AsR",
  EUROPE: "ER",
  NORTH_AMERICA: "NAR",
  OCEANIA: "OcR",
  SOUTH_AMERICA: "SAR",
};

export function getSuperRegion(regionCode: string): ContinentCode {
  const country = Countries.find((c) => c.code === regionCode);
  if (!country) throw new Error(`Unknown region code: ${regionCode}`);
  return country.superRegionCode;
}

export const Countries: {
  name: string;
  shortName?: string;
  code: string; // https://www.countrycallingcodes.com/iso-country-codes/
  superRegionCode: ContinentCode;
}[] = [
  { name: "Afghanistan", code: "AF", superRegionCode: "ASIA" },
  { name: "Albania", code: "AL", superRegionCode: "EUROPE" },
  { name: "Algeria", code: "DZ", superRegionCode: "AFRICA" },
  { name: "Andorra", code: "AD", superRegionCode: "EUROPE" },
  { name: "Angola", code: "AO", superRegionCode: "AFRICA" },
  { name: "Antigua and Barbuda", code: "AG", superRegionCode: "NORTH_AMERICA" },
  { name: "Argentina", code: "AR", superRegionCode: "SOUTH_AMERICA" },
  { name: "Armenia", code: "AM", superRegionCode: "EUROPE" },
  { name: "Australia", code: "AU", superRegionCode: "OCEANIA" },
  { name: "Austria", code: "AT", superRegionCode: "EUROPE" },
  { name: "Azerbaijan", code: "AZ", superRegionCode: "EUROPE" },
  { name: "Bahamas", code: "BS", superRegionCode: "NORTH_AMERICA" },
  { name: "Bahrain", code: "BH", superRegionCode: "ASIA" },
  { name: "Bangladesh", code: "BD", superRegionCode: "ASIA" },
  { name: "Barbados", code: "BB", superRegionCode: "NORTH_AMERICA" },
  { name: "Belarus", code: "BY", superRegionCode: "EUROPE" },
  { name: "Belgium", code: "BE", superRegionCode: "EUROPE" },
  { name: "Belize", code: "BZ", superRegionCode: "NORTH_AMERICA" },
  { name: "Benin", code: "BJ", superRegionCode: "AFRICA" },
  { name: "Bhutan", code: "BT", superRegionCode: "ASIA" },
  { name: "Bolivia", code: "BO", superRegionCode: "SOUTH_AMERICA" },
  { name: "Bosnia and Herzegovina", code: "BA", superRegionCode: "EUROPE" },
  { name: "Botswana", code: "BW", superRegionCode: "AFRICA" },
  { name: "Brazil", code: "BR", superRegionCode: "SOUTH_AMERICA" },
  { name: "Brunei", code: "BN", superRegionCode: "ASIA" },
  { name: "Bulgaria", code: "BG", superRegionCode: "EUROPE" },
  { name: "Burkina Faso", code: "BF", superRegionCode: "AFRICA" },
  { name: "Burundi", code: "BI", superRegionCode: "AFRICA" },
  { name: "Cabo Verde", code: "CV", superRegionCode: "AFRICA" },
  { name: "Cambodia", code: "KH", superRegionCode: "ASIA" },
  { name: "Cameroon", code: "CM", superRegionCode: "AFRICA" },
  { name: "Canada", code: "CA", superRegionCode: "NORTH_AMERICA" },
  { name: "Central African Republic", code: "CF", superRegionCode: "AFRICA" },
  { name: "Chad", code: "TD", superRegionCode: "AFRICA" },
  { name: "Chile", code: "CL", superRegionCode: "SOUTH_AMERICA" },
  { name: "China", code: "CN", superRegionCode: "ASIA" },
  { name: "Colombia", code: "CO", superRegionCode: "SOUTH_AMERICA" },
  { name: "Comoros", code: "KM", superRegionCode: "AFRICA" },
  { name: "Costa Rica", code: "CR", superRegionCode: "NORTH_AMERICA" },
  { name: "Côte d'Ivoire", code: "CI", superRegionCode: "AFRICA" },
  { name: "Croatia", code: "HR", superRegionCode: "EUROPE" },
  { name: "Cuba", code: "CU", superRegionCode: "NORTH_AMERICA" },
  { name: "Cyprus", code: "CY", superRegionCode: "EUROPE" },
  { name: "Czechia", code: "CZ", superRegionCode: "EUROPE" },
  { name: "Democratic Republic of the Congo", shortName: "DRC", code: "CD", superRegionCode: "AFRICA" },
  { name: "Denmark", code: "DK", superRegionCode: "EUROPE" },
  { name: "Djibouti", code: "DJ", superRegionCode: "AFRICA" },
  { name: "Dominica", code: "DM", superRegionCode: "NORTH_AMERICA" },
  { name: "Dominican Republic", code: "DO", superRegionCode: "NORTH_AMERICA" },
  { name: "Ecuador", code: "EC", superRegionCode: "SOUTH_AMERICA" },
  { name: "Egypt", code: "EG", superRegionCode: "AFRICA" },
  { name: "El Salvador", code: "SV", superRegionCode: "NORTH_AMERICA" },
  { name: "Equatorial Guinea", code: "GQ", superRegionCode: "AFRICA" },
  { name: "Eritrea", code: "ER", superRegionCode: "AFRICA" },
  { name: "Estonia", code: "EE", superRegionCode: "EUROPE" },
  { name: "Eswatini", code: "SZ", superRegionCode: "AFRICA" },
  { name: "Ethiopia", code: "ET", superRegionCode: "AFRICA" },
  { name: "Fiji", code: "FJ", superRegionCode: "OCEANIA" },
  { name: "Finland", code: "FI", superRegionCode: "EUROPE" },
  { name: "France", code: "FR", superRegionCode: "EUROPE" },
  { name: "Gabon", code: "GA", superRegionCode: "AFRICA" },
  { name: "Gambia", code: "GM", superRegionCode: "AFRICA" },
  { name: "Georgia", code: "GE", superRegionCode: "EUROPE" },
  { name: "Germany", code: "DE", superRegionCode: "EUROPE" },
  { name: "Ghana", code: "GH", superRegionCode: "AFRICA" },
  { name: "Greece", code: "GR", superRegionCode: "EUROPE" },
  { name: "Grenada", code: "GD", superRegionCode: "NORTH_AMERICA" },
  { name: "Guatemala", code: "GT", superRegionCode: "NORTH_AMERICA" },
  { name: "Guinea", code: "GN", superRegionCode: "AFRICA" },
  { name: "Guinea Bissau", code: "GW", superRegionCode: "AFRICA" },
  { name: "Guyana", code: "GY", superRegionCode: "SOUTH_AMERICA" },
  { name: "Haiti", code: "HT", superRegionCode: "NORTH_AMERICA" },
  { name: "Honduras", code: "HN", superRegionCode: "NORTH_AMERICA" },
  { name: "Hong Kong", code: "HK", superRegionCode: "ASIA" },
  { name: "Hungary", code: "HU", superRegionCode: "EUROPE" },
  { name: "Iceland", code: "IS", superRegionCode: "EUROPE" },
  { name: "India", code: "IN", superRegionCode: "ASIA" },
  { name: "Indonesia", code: "ID", superRegionCode: "ASIA" },
  { name: "Iran", code: "IR", superRegionCode: "ASIA" },
  { name: "Iraq", code: "IQ", superRegionCode: "ASIA" },
  { name: "Ireland", code: "IE", superRegionCode: "EUROPE" },
  { name: "Israel", code: "IL", superRegionCode: "EUROPE" },
  { name: "Italy", code: "IT", superRegionCode: "EUROPE" },
  { name: "Jamaica", code: "JM", superRegionCode: "NORTH_AMERICA" },
  { name: "Japan", code: "JP", superRegionCode: "ASIA" },
  { name: "Jordan", code: "JO", superRegionCode: "ASIA" },
  { name: "Kazakhstan", code: "KZ", superRegionCode: "ASIA" },
  { name: "Kenya", code: "KE", superRegionCode: "AFRICA" },
  { name: "Kiribati", code: "KI", superRegionCode: "OCEANIA" },
  { name: "Kosovo", code: "XK", superRegionCode: "EUROPE" },
  { name: "Kuwait", code: "KW", superRegionCode: "ASIA" },
  { name: "Kyrgyzstan", code: "KG", superRegionCode: "ASIA" },
  { name: "Laos", code: "LA", superRegionCode: "ASIA" },
  { name: "Latvia", code: "LV", superRegionCode: "EUROPE" },
  { name: "Lebanon", code: "LB", superRegionCode: "ASIA" },
  { name: "Lesotho", code: "LS", superRegionCode: "AFRICA" },
  { name: "Liberia", code: "LR", superRegionCode: "AFRICA" },
  { name: "Libya", code: "LY", superRegionCode: "AFRICA" },
  { name: "Liechtenstein", code: "LI", superRegionCode: "EUROPE" },
  { name: "Lithuania", code: "LT", superRegionCode: "EUROPE" },
  { name: "Luxembourg", code: "LU", superRegionCode: "EUROPE" },
  { name: "Macau", code: "MO", superRegionCode: "ASIA" },
  { name: "Madagascar", code: "MG", superRegionCode: "AFRICA" },
  { name: "Malawi", code: "MW", superRegionCode: "AFRICA" },
  { name: "Malaysia", code: "MY", superRegionCode: "ASIA" },
  { name: "Maldives", code: "MV", superRegionCode: "ASIA" },
  { name: "Mali", code: "ML", superRegionCode: "AFRICA" },
  { name: "Malta", code: "MT", superRegionCode: "EUROPE" },
  { name: "Marshall Islands", code: "MH", superRegionCode: "OCEANIA" },
  { name: "Mauritania", code: "MR", superRegionCode: "AFRICA" },
  { name: "Mauritius", code: "MU", superRegionCode: "AFRICA" },
  { name: "Mexico", code: "MX", superRegionCode: "NORTH_AMERICA" },
  { name: "Micronesia", code: "FM", superRegionCode: "OCEANIA" },
  { name: "Moldova", code: "MD", superRegionCode: "EUROPE" },
  { name: "Monaco", code: "MC", superRegionCode: "EUROPE" },
  { name: "Mongolia", code: "MN", superRegionCode: "ASIA" },
  { name: "Montenegro", code: "ME", superRegionCode: "EUROPE" },
  { name: "Morocco", code: "MA", superRegionCode: "AFRICA" },
  { name: "Mozambique", code: "MZ", superRegionCode: "AFRICA" },
  { name: "Myanmar", code: "MM", superRegionCode: "ASIA" },
  { name: "Namibia", code: "NA", superRegionCode: "AFRICA" },
  { name: "Nauru", code: "NR", superRegionCode: "OCEANIA" },
  { name: "Nepal", code: "NP", superRegionCode: "ASIA" },
  { name: "Netherlands", code: "NL", superRegionCode: "EUROPE" },
  { name: "New Zealand", code: "NZ", superRegionCode: "OCEANIA" },
  { name: "Nicaragua", code: "NI", superRegionCode: "NORTH_AMERICA" },
  { name: "Niger", code: "NE", superRegionCode: "AFRICA" },
  { name: "Nigeria", code: "NG", superRegionCode: "AFRICA" },
  { name: "North Korea", code: "KP", superRegionCode: "ASIA" },
  { name: "North Macedonia", code: "MK", superRegionCode: "EUROPE" },
  { name: "Norway", code: "NO", superRegionCode: "EUROPE" },
  { name: "Oman", code: "OM", superRegionCode: "ASIA" },
  { name: "Pakistan", code: "PK", superRegionCode: "ASIA" },
  { name: "Palau", code: "PW", superRegionCode: "OCEANIA" },
  { name: "Palestine", code: "PS", superRegionCode: "ASIA" },
  { name: "Panama", code: "PA", superRegionCode: "NORTH_AMERICA" },
  { name: "Papua New Guinea", code: "PG", superRegionCode: "OCEANIA" },
  { name: "Paraguay", code: "PY", superRegionCode: "SOUTH_AMERICA" },
  { name: "Peru", code: "PE", superRegionCode: "SOUTH_AMERICA" },
  { name: "Philippines", code: "PH", superRegionCode: "ASIA" },
  { name: "Poland", code: "PL", superRegionCode: "EUROPE" },
  { name: "Portugal", code: "PT", superRegionCode: "EUROPE" },
  { name: "Qatar", code: "QA", superRegionCode: "ASIA" },
  { name: "Republic of the Congo", code: "CG", superRegionCode: "AFRICA" },
  { name: "Romania", code: "RO", superRegionCode: "EUROPE" },
  { name: "Russia", code: "RU", superRegionCode: "EUROPE" },
  { name: "Rwanda", code: "RW", superRegionCode: "AFRICA" },
  { name: "Saint Kitts and Nevis", code: "KN", superRegionCode: "NORTH_AMERICA" },
  { name: "Saint Lucia", code: "LC", superRegionCode: "NORTH_AMERICA" },
  { name: "Saint Vincent and the Grenadines", code: "VC", superRegionCode: "NORTH_AMERICA" },
  { name: "Samoa", code: "WS", superRegionCode: "OCEANIA" },
  { name: "San Marino", code: "SM", superRegionCode: "EUROPE" },
  { name: "São Tomé and Príncipe", code: "ST", superRegionCode: "AFRICA" },
  { name: "Saudi Arabia", code: "SA", superRegionCode: "ASIA" },
  { name: "Senegal", code: "SN", superRegionCode: "AFRICA" },
  { name: "Serbia", code: "RS", superRegionCode: "EUROPE" },
  { name: "Seychelles", code: "SC", superRegionCode: "AFRICA" },
  { name: "Sierra Leone", code: "SL", superRegionCode: "AFRICA" },
  { name: "Singapore", code: "SG", superRegionCode: "ASIA" },
  { name: "Slovakia", code: "SK", superRegionCode: "EUROPE" },
  { name: "Slovenia", code: "SI", superRegionCode: "EUROPE" },
  { name: "Solomon Islands", code: "SB", superRegionCode: "OCEANIA" },
  { name: "Somalia", code: "SO", superRegionCode: "AFRICA" },
  { name: "South Africa", code: "ZA", superRegionCode: "AFRICA" },
  { name: "South Korea", code: "KR", superRegionCode: "ASIA" },
  { name: "South Sudan", code: "SS", superRegionCode: "AFRICA" },
  { name: "Spain", code: "ES", superRegionCode: "EUROPE" },
  { name: "Sri Lanka", code: "LK", superRegionCode: "ASIA" },
  { name: "Sudan", code: "SD", superRegionCode: "AFRICA" },
  { name: "Suriname", code: "SR", superRegionCode: "SOUTH_AMERICA" },
  { name: "Sweden", code: "SE", superRegionCode: "EUROPE" },
  { name: "Switzerland", code: "CH", superRegionCode: "EUROPE" },
  { name: "Syria", code: "SY", superRegionCode: "ASIA" },
  { name: "Taiwan", code: "TW", superRegionCode: "ASIA" },
  { name: "Tajikistan", code: "TJ", superRegionCode: "ASIA" },
  { name: "Tanzania", code: "TZ", superRegionCode: "AFRICA" },
  { name: "Thailand", code: "TH", superRegionCode: "ASIA" },
  { name: "Timor-Leste", code: "TL", superRegionCode: "ASIA" },
  { name: "Togo", code: "TG", superRegionCode: "AFRICA" },
  { name: "Tonga", code: "TO", superRegionCode: "OCEANIA" },
  { name: "Trinidad and Tobago", code: "TT", superRegionCode: "NORTH_AMERICA" },
  { name: "Tunisia", code: "TN", superRegionCode: "AFRICA" },
  { name: "Turkmenistan", code: "TM", superRegionCode: "ASIA" },
  { name: "Tuvalu", code: "TV", superRegionCode: "OCEANIA" },
  { name: "Türkiye", code: "TR", superRegionCode: "EUROPE" },
  { name: "Uganda", code: "UG", superRegionCode: "AFRICA" },
  { name: "Ukraine", code: "UA", superRegionCode: "EUROPE" },
  { name: "United Arab Emirates", shortName: "UAE", code: "AE", superRegionCode: "ASIA" },
  { name: "United Kingdom", shortName: "UK", code: "GB", superRegionCode: "EUROPE" },
  { name: "United States", shortName: "USA", code: "US", superRegionCode: "NORTH_AMERICA" },
  { name: "Uruguay", code: "UY", superRegionCode: "SOUTH_AMERICA" },
  { name: "Uzbekistan", code: "UZ", superRegionCode: "ASIA" },
  { name: "Vanuatu", code: "VU", superRegionCode: "OCEANIA" },
  { name: "Vatican City", code: "VA", superRegionCode: "EUROPE" },
  { name: "Venezuela", code: "VE", superRegionCode: "SOUTH_AMERICA" },
  { name: "Vietnam", code: "VN", superRegionCode: "ASIA" },
  { name: "Yemen", code: "YE", superRegionCode: "ASIA" },
  { name: "Zambia", code: "ZM", superRegionCode: "AFRICA" },
  { name: "Zimbabwe", code: "ZW", superRegionCode: "AFRICA" },
];

export const CountryCodes = Countries.map((c) => c.code);
