#!/bin/bash

# The environment variables are coming from the container (see docker-compose.yml)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';
CREATE DATABASE $DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USERNAME;
ALTER DATABASE $DB_NAME OWNER TO $DB_USERNAME;
EOSQL
