interface ICompetition {
  competitionId: string;
  name: string;
  city: string;
  countryId: string;
  startDate: Date;
  endDate: Date;
  // Only set if the competition results have been posted
  events?: {
    eventId: string;
    rounds: string[]; // array of round ids (the _id values generated by Mongo)
  }[];
  mainEventId: string;
}

export default ICompetition;
